### ISSUE TITLE
turbine: how to make clusters work

### ISSUE THREAD

**Issue by caarlos0** [fabric8io/kubeflix#182]
I've tried to make the `?cluster=blah` work, but it won't. I'm pretty sure I'm missing something, but I'm not really sure what.

So far, I'm creating everything with this yaml:

```yaml
---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "turbine"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    project: "turbine-server"
    provider: "fabric8"
    version: "1.0.28"
    group: "io.fabric8.kubeflix"
  name: "turbine-server"
spec:
  replicas: 1
  selector:
    matchLabels:
      project: "turbine-server"
      provider: "fabric8"
      group: "io.fabric8.kubeflix"
  template:
    metadata:
      labels:
        project: "turbine-server"
        provider: "fabric8"
        version: "1.0.28"
        group: "io.fabric8.kubeflix"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/turbine-server:1.0.28"
        name: "turbine-server"
        ports:
        - containerPort: 8080
          name: "http"
        - containerPort: 8778
          name: "jolokia"
      serviceAccountName: "turbine"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    servicepath: "/turbine.stream"
  labels:
    project: "turbine-server"
    provider: "fabric8"
    version: "1.0.28"
    group: "io.fabric8.kubeflix"
  name: "turbine-server"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "turbine-server"
    provider: "fabric8"
    group: "io.fabric8.kubeflix"
  type: "LoadBalancer"
```

I also enabled some services by annotating them:

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    hystrix.enabled: "true"
    hystrix.cluster: "svc1"
```

I'm not sure where I should put them, though. Should it be in the service or in the deployment?

Anyways, by doing this, I can access the `turbine-server` ELB addr + `/turbine.stream`, but, if a append a `?cluster=svc1` in the URL, I get a 404.

Seems like I'm missing some turbine configs, but I'm not sure how to do it and there is no example in the docs...

Thanks!
